
social = Category.create(name: 'Social')
health = Category.create(name: 'Health')
intellect =  Category.create(name: 'Intellect')

user1 = User.create(email: "foo@bar.com", first_name: "Rick", last_name: "James", password: "foobarbar", password_confirmation: "foobarbar")
realchart_user1 = RealChart.create(user_id: user1.id)
act1 = Activity.create(category_id: social.id, real_chart_id: 1, body: "call grandma")
act2 = Activity.create(category_id: health.id, real_chart_id: 1, body: "walk with grandma")
act3 = Activity.create(category_id: intellect.id, real_chart_id: 1, body: "study grandma")
act4 = Activity.create(category_id: social.id, real_chart_id: 1, body: "eat with grandma")
Interest.create(user_id: user1.id, activity_id: act1.id)
Interest.create(user_id: user1.id, activity_id: act2.id)
Interest.create(user_id: user1.id, activity_id: act3.id)
ideal1 = IdealChart.create(user_id: user1.id, health_score: 33, social_score: 30 , intellect_score: 47)
