
social = Category.create(name: 'Social')
health = Category.create(name: 'Health')
intellect =  Category.create(name: 'Intellect')

user1 = User.create(email: "foo@bar.com", first_name: "Rick", last_name: "James", password: "foobarbar", password_confirmation: "foobarbar")
ideal1 = IdealChart.create(user_id: user1.id, health_score: 33, social_score: 30 , intellect_score: 47)
#user1 interests
act1 = Activity.create(category_id: social.id, body: "call grandma")
act2 = Activity.create(category_id: health.id, body: "walk with grandma")
act3 = Activity.create(category_id: intellect.id, body: "study grandma")
act4 = Activity.create(category_id: social.id, body: "eat with grandma")
act5 = Activity.create(category_id: social.id, body: "go to bars")
act6 = Activity.create(category_id: health.id, body: "eat vitamins")
act7 = Activity.create(category_id: intellect.id, body: "study everything")
Interest.create(user_id: user1.id, activity_id: act1.id)
Interest.create(user_id: user1.id, activity_id: act2.id)
Interest.create(user_id: user1.id, activity_id: act3.id)
Interest.create(user_id: user1.id, activity_id: act5.id)
Interest.create(user_id: user1.id, activity_id: act6.id)
Interest.create(user_id: user1.id, activity_id: act7.id)

#user1 real chart & real chart activities
real1 = RealChart.create(user_id: user1.id)
act1 = Activity.create(category_id: social.id, body: "called grandma", real_chart_id: real1.id, created_at: "2014-02-20 01:32:00", updated_at: "2014-02-20 01:32:00")
act2 = Activity.create(category_id: health.id, body: "walked with grandma", real_chart_id: real1.id, created_at: "2014-02-20 09:00:00", updated_at: "2014-02-20 09:00:00")
act3 = Activity.create(category_id: intellect.id, body: "studied grandma", real_chart_id: real1.id, created_at: "2014-02-19 11:17:06", updated_at: "2014-02-20 11:17:06")
act4 = Activity.create(category_id: social.id, body: "ate with grandma", real_chart_id: real1.id, created_at: "2014-02-19 03:17:06", updated_at: "2014-02-19 03:17:06")
act5 = Activity.create(category_id: social.id, body: "spent birthday with Alex", real_chart_id: real1.id, created_at: "2014-02-19 03:17:06", updated_at: "2014-02-19 03:17:06")
act6 = Activity.create(category_id: health.id, body: "took my fish oil", real_chart_id: real1.id, created_at: "2014-02-18 03:17:06", updated_at: "2014-02-18 03:17:06")
act7 = Activity.create(category_id: intellect.id, body: "talked about philosophy", real_chart_id: real1.id, created_at: "2014-02-18 03:17:06", updated_at: "2014-02-18 03:17:06")